name: Build APK

on:
  push:
    branches:
      - main  # Cambiar por el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v3
      with:
        flutter-version: '3.19.3'  # O la versión de Flutter que desees utilizar

    - name: Check Flutter version
      run: flutter --version
      
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Cambiar por la versión de Java que necesites
      
    - name: Build with Flutter
      run: flutter build apk --release  # Comando para construir la APK
      
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk  # Ruta al APK generado