name: Build APK

on:
  push:
    branches:
      - main  # Cambiar por el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Flutter version
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'  # Cambiar por la versi√≥n de Java que necesites
      
    - name: Build with Flutter
      run: flutter build apk  # Comando para construir la APK
      
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: WealthWars
        path: app/build/outputs/apk/debug/WealthWars.apk  # Ruta al APK generado