name: Build APK

on:
  push:
    branches:
      - main  # Cambiar por el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Builds - build Flutter APK and create github release
      uses: Dank-del/flutter-build-and-publish-action@v1